name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        os: [win]
        configuration: [Debug, Release]
        arch: [x86, x64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: piconavx-host.sln
      Project_Path: piconavxui/piconavxui.csproj
      Project_Directory: piconavxui

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    # Disable to save compute time
    # - name: Execute unit tests
    #   run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    # Create the app binary by building the project
    - name: Create app binary
      run: dotnet publish $env:Project_Path --arch $env:Arch --configuration $env:Configuration --os $env:Os --self-contained true --output $env:Project_Directory\publish\$env:Os-$env:Arch-$env:Configuration\ -p:PublishReadyToRun=true -p:PublishSingleFile=true
      env:
        Configuration: ${{ matrix.configuration }}
        Arch: ${{ matrix.arch }}
        Os: ${{ matrix.os }}

    # Upload the published binary: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.configuration }}
        path: ${{ env.Project_Directory }}\publish\${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.configuration }}\
        retention-days: 3
